//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementWebClientapplication.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.RoomManagementServiceSoap")]
    public interface RoomManagementServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertHotels(string Name, string Address, string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertHotelsAsync(string Name, string Address, string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int updateHotels(string Name, string Address, string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<int> updateHotelsAsync(string Name, string Address, string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int deleteHotels(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<int> deleteHotelsAsync(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchHotels(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchHotelsAsync(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchAllHotels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchAllHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchAllHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchAllHotelsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RoomManagementServiceSoapChannel : HotelManagementWebClientapplication.ServiceReference1.RoomManagementServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomManagementServiceSoapClient : System.ServiceModel.ClientBase<HotelManagementWebClientapplication.ServiceReference1.RoomManagementServiceSoap>, HotelManagementWebClientapplication.ServiceReference1.RoomManagementServiceSoap {
        
        public RoomManagementServiceSoapClient() {
        }
        
        public RoomManagementServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomManagementServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomManagementServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomManagementServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertHotels(string Name, string Address, string UserName, string Password) {
            return base.Channel.insertHotels(Name, Address, UserName, Password);
        }
        
        public System.Threading.Tasks.Task<int> insertHotelsAsync(string Name, string Address, string UserName, string Password) {
            return base.Channel.insertHotelsAsync(Name, Address, UserName, Password);
        }
        
        public int updateHotels(string Name, string Address, string UserName, string Password) {
            return base.Channel.updateHotels(Name, Address, UserName, Password);
        }
        
        public System.Threading.Tasks.Task<int> updateHotelsAsync(string Name, string Address, string UserName, string Password) {
            return base.Channel.updateHotelsAsync(Name, Address, UserName, Password);
        }
        
        public int deleteHotels(string UserName) {
            return base.Channel.deleteHotels(UserName);
        }
        
        public System.Threading.Tasks.Task<int> deleteHotelsAsync(string UserName) {
            return base.Channel.deleteHotelsAsync(UserName);
        }
        
        public System.Data.DataSet searchHotels(string UserName) {
            return base.Channel.searchHotels(UserName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchHotelsAsync(string UserName) {
            return base.Channel.searchHotelsAsync(UserName);
        }
        
        public System.Data.DataSet searchAllHotels() {
            return base.Channel.searchAllHotels();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchAllHotelsAsync() {
            return base.Channel.searchAllHotelsAsync();
        }
    }
}
