//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HotelManagementSystemProject.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RoomManagementServiceSoap", Namespace="http://tempuri.org/")]
    public partial class RoomManagementService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insertHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchAllHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchRoomsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchAllRoomsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RoomManagementService() {
            this.Url = global::HotelManagementSystemProject.Properties.Settings.Default.HotelManagementSystemProject_localhost_RoomManagementService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insertHotelsCompletedEventHandler insertHotelsCompleted;
        
        /// <remarks/>
        public event updateHotelsCompletedEventHandler updateHotelsCompleted;
        
        /// <remarks/>
        public event deleteHotelsCompletedEventHandler deleteHotelsCompleted;
        
        /// <remarks/>
        public event searchHotelsCompletedEventHandler searchHotelsCompleted;
        
        /// <remarks/>
        public event searchAllHotelsCompletedEventHandler searchAllHotelsCompleted;
        
        /// <remarks/>
        public event insertRoomsCompletedEventHandler insertRoomsCompleted;
        
        /// <remarks/>
        public event updateRoomsCompletedEventHandler updateRoomsCompleted;
        
        /// <remarks/>
        public event deleteRoomsCompletedEventHandler deleteRoomsCompleted;
        
        /// <remarks/>
        public event searchRoomsCompletedEventHandler searchRoomsCompleted;
        
        /// <remarks/>
        public event SearchAllRoomsCompletedEventHandler SearchAllRoomsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertHotels(string Name, string Address, string UserName, string Password) {
            object[] results = this.Invoke("insertHotels", new object[] {
                        Name,
                        Address,
                        UserName,
                        Password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertHotelsAsync(string Name, string Address, string UserName, string Password) {
            this.insertHotelsAsync(Name, Address, UserName, Password, null);
        }
        
        /// <remarks/>
        public void insertHotelsAsync(string Name, string Address, string UserName, string Password, object userState) {
            if ((this.insertHotelsOperationCompleted == null)) {
                this.insertHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertHotelsOperationCompleted);
            }
            this.InvokeAsync("insertHotels", new object[] {
                        Name,
                        Address,
                        UserName,
                        Password}, this.insertHotelsOperationCompleted, userState);
        }
        
        private void OninsertHotelsOperationCompleted(object arg) {
            if ((this.insertHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertHotelsCompleted(this, new insertHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int updateHotels(int id, string Name, string Address, string UserName, string Password) {
            object[] results = this.Invoke("updateHotels", new object[] {
                        id,
                        Name,
                        Address,
                        UserName,
                        Password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void updateHotelsAsync(int id, string Name, string Address, string UserName, string Password) {
            this.updateHotelsAsync(id, Name, Address, UserName, Password, null);
        }
        
        /// <remarks/>
        public void updateHotelsAsync(int id, string Name, string Address, string UserName, string Password, object userState) {
            if ((this.updateHotelsOperationCompleted == null)) {
                this.updateHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateHotelsOperationCompleted);
            }
            this.InvokeAsync("updateHotels", new object[] {
                        id,
                        Name,
                        Address,
                        UserName,
                        Password}, this.updateHotelsOperationCompleted, userState);
        }
        
        private void OnupdateHotelsOperationCompleted(object arg) {
            if ((this.updateHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateHotelsCompleted(this, new updateHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteHotels(int id) {
            object[] results = this.Invoke("deleteHotels", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteHotelsAsync(int id) {
            this.deleteHotelsAsync(id, null);
        }
        
        /// <remarks/>
        public void deleteHotelsAsync(int id, object userState) {
            if ((this.deleteHotelsOperationCompleted == null)) {
                this.deleteHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteHotelsOperationCompleted);
            }
            this.InvokeAsync("deleteHotels", new object[] {
                        id}, this.deleteHotelsOperationCompleted, userState);
        }
        
        private void OndeleteHotelsOperationCompleted(object arg) {
            if ((this.deleteHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteHotelsCompleted(this, new deleteHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet searchHotels(int id) {
            object[] results = this.Invoke("searchHotels", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void searchHotelsAsync(int id) {
            this.searchHotelsAsync(id, null);
        }
        
        /// <remarks/>
        public void searchHotelsAsync(int id, object userState) {
            if ((this.searchHotelsOperationCompleted == null)) {
                this.searchHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchHotelsOperationCompleted);
            }
            this.InvokeAsync("searchHotels", new object[] {
                        id}, this.searchHotelsOperationCompleted, userState);
        }
        
        private void OnsearchHotelsOperationCompleted(object arg) {
            if ((this.searchHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchHotelsCompleted(this, new searchHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchAllHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet searchAllHotels() {
            object[] results = this.Invoke("searchAllHotels", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void searchAllHotelsAsync() {
            this.searchAllHotelsAsync(null);
        }
        
        /// <remarks/>
        public void searchAllHotelsAsync(object userState) {
            if ((this.searchAllHotelsOperationCompleted == null)) {
                this.searchAllHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchAllHotelsOperationCompleted);
            }
            this.InvokeAsync("searchAllHotels", new object[0], this.searchAllHotelsOperationCompleted, userState);
        }
        
        private void OnsearchAllHotelsOperationCompleted(object arg) {
            if ((this.searchAllHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchAllHotelsCompleted(this, new searchAllHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int insertRooms(string HotelName, int RID, string RType, string RCountry, string RCity, string RDetails, string RContact, string RPrice, string RAvailble) {
            object[] results = this.Invoke("insertRooms", new object[] {
                        HotelName,
                        RID,
                        RType,
                        RCountry,
                        RCity,
                        RDetails,
                        RContact,
                        RPrice,
                        RAvailble});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void insertRoomsAsync(string HotelName, int RID, string RType, string RCountry, string RCity, string RDetails, string RContact, string RPrice, string RAvailble) {
            this.insertRoomsAsync(HotelName, RID, RType, RCountry, RCity, RDetails, RContact, RPrice, RAvailble, null);
        }
        
        /// <remarks/>
        public void insertRoomsAsync(string HotelName, int RID, string RType, string RCountry, string RCity, string RDetails, string RContact, string RPrice, string RAvailble, object userState) {
            if ((this.insertRoomsOperationCompleted == null)) {
                this.insertRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertRoomsOperationCompleted);
            }
            this.InvokeAsync("insertRooms", new object[] {
                        HotelName,
                        RID,
                        RType,
                        RCountry,
                        RCity,
                        RDetails,
                        RContact,
                        RPrice,
                        RAvailble}, this.insertRoomsOperationCompleted, userState);
        }
        
        private void OninsertRoomsOperationCompleted(object arg) {
            if ((this.insertRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertRoomsCompleted(this, new insertRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int updateRooms(string HotelName, int RID, string RType, string RCountry, string RCity, string RDetails, string RContact, string RPrice, string RAvailble) {
            object[] results = this.Invoke("updateRooms", new object[] {
                        HotelName,
                        RID,
                        RType,
                        RCountry,
                        RCity,
                        RDetails,
                        RContact,
                        RPrice,
                        RAvailble});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void updateRoomsAsync(string HotelName, int RID, string RType, string RCountry, string RCity, string RDetails, string RContact, string RPrice, string RAvailble) {
            this.updateRoomsAsync(HotelName, RID, RType, RCountry, RCity, RDetails, RContact, RPrice, RAvailble, null);
        }
        
        /// <remarks/>
        public void updateRoomsAsync(string HotelName, int RID, string RType, string RCountry, string RCity, string RDetails, string RContact, string RPrice, string RAvailble, object userState) {
            if ((this.updateRoomsOperationCompleted == null)) {
                this.updateRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateRoomsOperationCompleted);
            }
            this.InvokeAsync("updateRooms", new object[] {
                        HotelName,
                        RID,
                        RType,
                        RCountry,
                        RCity,
                        RDetails,
                        RContact,
                        RPrice,
                        RAvailble}, this.updateRoomsOperationCompleted, userState);
        }
        
        private void OnupdateRoomsOperationCompleted(object arg) {
            if ((this.updateRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateRoomsCompleted(this, new updateRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int deleteRooms(int RID) {
            object[] results = this.Invoke("deleteRooms", new object[] {
                        RID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void deleteRoomsAsync(int RID) {
            this.deleteRoomsAsync(RID, null);
        }
        
        /// <remarks/>
        public void deleteRoomsAsync(int RID, object userState) {
            if ((this.deleteRoomsOperationCompleted == null)) {
                this.deleteRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteRoomsOperationCompleted);
            }
            this.InvokeAsync("deleteRooms", new object[] {
                        RID}, this.deleteRoomsOperationCompleted, userState);
        }
        
        private void OndeleteRoomsOperationCompleted(object arg) {
            if ((this.deleteRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteRoomsCompleted(this, new deleteRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet searchRooms(int RID) {
            object[] results = this.Invoke("searchRooms", new object[] {
                        RID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void searchRoomsAsync(int RID) {
            this.searchRoomsAsync(RID, null);
        }
        
        /// <remarks/>
        public void searchRoomsAsync(int RID, object userState) {
            if ((this.searchRoomsOperationCompleted == null)) {
                this.searchRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchRoomsOperationCompleted);
            }
            this.InvokeAsync("searchRooms", new object[] {
                        RID}, this.searchRoomsOperationCompleted, userState);
        }
        
        private void OnsearchRoomsOperationCompleted(object arg) {
            if ((this.searchRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchRoomsCompleted(this, new searchRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchAllRooms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SearchAllRooms() {
            object[] results = this.Invoke("SearchAllRooms", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SearchAllRoomsAsync() {
            this.SearchAllRoomsAsync(null);
        }
        
        /// <remarks/>
        public void SearchAllRoomsAsync(object userState) {
            if ((this.SearchAllRoomsOperationCompleted == null)) {
                this.SearchAllRoomsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchAllRoomsOperationCompleted);
            }
            this.InvokeAsync("SearchAllRooms", new object[0], this.SearchAllRoomsOperationCompleted, userState);
        }
        
        private void OnSearchAllRoomsOperationCompleted(object arg) {
            if ((this.SearchAllRoomsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchAllRoomsCompleted(this, new SearchAllRoomsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertHotelsCompletedEventHandler(object sender, insertHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void updateHotelsCompletedEventHandler(object sender, updateHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteHotelsCompletedEventHandler(object sender, deleteHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void searchHotelsCompletedEventHandler(object sender, searchHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void searchAllHotelsCompletedEventHandler(object sender, searchAllHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchAllHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchAllHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void insertRoomsCompletedEventHandler(object sender, insertRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void updateRoomsCompletedEventHandler(object sender, updateRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteRoomsCompletedEventHandler(object sender, deleteRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void searchRoomsCompletedEventHandler(object sender, searchRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SearchAllRoomsCompletedEventHandler(object sender, SearchAllRoomsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchAllRoomsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchAllRoomsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591